// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbYE4iTdDHeXO063qzY4zpzkxO3AKn4BQ',
    appId: '1:570318020676:web:8f9707125bc33a34a7dc11',
    messagingSenderId: '570318020676',
    projectId: 'danielbarbershop-53e3f',
    authDomain: 'danielbarbershop-53e3f.firebaseapp.com',
    storageBucket: 'danielbarbershop-53e3f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZyqs7UH_Vl2STvrrVYZRYEr_GLz4IYq8',
    appId: '1:570318020676:android:d941742e46e13f29a7dc11',
    messagingSenderId: '570318020676',
    projectId: 'danielbarbershop-53e3f',
    storageBucket: 'danielbarbershop-53e3f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbYE4iTdDHeXO063qzY4zpzkxO3AKn4BQ',
    appId: '1:570318020676:web:859539a933a722eca7dc11',
    messagingSenderId: '570318020676',
    projectId: 'danielbarbershop-53e3f',
    authDomain: 'danielbarbershop-53e3f.firebaseapp.com',
    storageBucket: 'danielbarbershop-53e3f.firebasestorage.app',
  );
}
