// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDqQ3pwmxEFY7mBve2wRGgop4nLBjyHjQ',
    appId: '1:593847407002:web:2308812d7159e4aaef6a23',
    messagingSenderId: '593847407002',
    projectId: 'supercolor-25505',
    authDomain: 'supercolor-25505.firebaseapp.com',
    storageBucket: 'supercolor-25505.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZfwfPmjOb7ynSDL66BaI2mHnLtbTizbc',
    appId: '1:593847407002:android:83e8d55370a9dad5ef6a23',
    messagingSenderId: '593847407002',
    projectId: 'supercolor-25505',
    storageBucket: 'supercolor-25505.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDqQ3pwmxEFY7mBve2wRGgop4nLBjyHjQ',
    appId: '1:593847407002:web:f1b7379182d091a0ef6a23',
    messagingSenderId: '593847407002',
    projectId: 'supercolor-25505',
    authDomain: 'supercolor-25505.firebaseapp.com',
    storageBucket: 'supercolor-25505.firebasestorage.app',
  );
}
